services:
  expresserver:
    build: .

    ports:
      - ${PORT}:${PORT}
    
    environment:
      - CONNECTION_STRING=mongodb://usuario:senhaGenerica10@mongodbServer:27017/senhasApp?authSource=admin
    
  mongodbServer:
    image: clutteredcode/mongo-alpine:latest

    container_name: mongodbServer

    ports:
      - 27017:27017
    environment:
      - MONGO_USERNAME=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}